[package]
name = "mini"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "3.2.23" }
colored = { version = "2.0.0"}
indexmap = { version = "1.9.2"}
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
logos = { version = "0.12.1" }
regex = { version = "1" }

[build-dependencies]
lalrpop = { version = "0.19.8", features = ["lexer"] }

[workspace]
members = ["library"]
default-members = ["library"]
